### ISSUE TITLE
java.lang.IllegalArgumentException: The concrete class implementing IObjectWrapper

### ISSUE THREAD

**Issue by sarathsi** [google-ar/WebARonARCore#28]
Hi ,
I have built the APK from source and trying to run. App is crashing during the startup. 

10-25 12:48:32.323 20583 20583 E AndroidRuntime: java.lang.IllegalArgumentException: The concrete class implementing IObjectWrapper must have exactly *one* declared private field for the wrapped object.  Preferably, this is an instance of the ObjectWrapper<T> class.

Any clues how to solve this issue?

logcat:
++++++++++++++++++++
10-25 12:48:32.294 20583 20583 I TangoClientLibLoader: Pure Java path, not loading libtango_client_api.so at all.
10-25 12:48:32.316 20583 20583 I ndk_camera: Starting native camera system initialization.
10-25 12:48:32.319 20583 20583 D ndk_camera: Camera 0 has 83 metadata tags
10-25 12:48:32.319 20583 20583 E ACameraMetadata: getConstEntry: cannot find metadata tag 1310721
10-25 12:48:32.319 20583 20583 W ndk_camera: Failed to get metadata tag 1310721 for camera 0 with error code -10004
10-25 12:48:32.319 20583 20583 E ACameraMetadata: getConstEntry: cannot find metadata tag 1638401
10-25 12:48:32.319 20583 20583 W ndk_camera: Failed to get metadata tag 1638401 for camera 0 with error code -10004
10-25 12:48:32.320 20583 20583 D ndk_camera: Camera 1 has 82 metadata tags
10-25 12:48:32.320 20583 20583 E ACameraMetadata: getConstEntry: cannot find metadata tag 1310721
10-25 12:48:32.320 20583 20583 W ndk_camera: Failed to get metadata tag 1310721 for camera 1 with error code -10004
10-25 12:48:32.320 20583 20583 E ACameraMetadata: getConstEntry: cannot find metadata tag 1638401
10-25 12:48:32.320 20583 20583 W ndk_camera: Failed to get metadata tag 1638401 for camera 1 with error code -10004
10-25 12:48:32.320 20583 20583 I ndk_camera: Camera system initialized successfully with 2 cameras.
10-25 12:48:32.320 20583 20583 W tango_camera_native_jni: Camera system initilized.
10-25 12:48:32.320 20583 20583 E tango_camera_native: 2 is not a valid camera index.
10-25 12:48:32.320 20583 20583 E tango_camera_native: 3 is not a valid camera index.
10-25 12:48:32.322 20583 20583 D AndroidRuntime: Shutting down VM

--------- beginning of crash
10-25 12:48:32.323 20583 20583 E AndroidRuntime: FATAL EXCEPTION: main
10-25 12:48:32.323 20583 20583 E AndroidRuntime: java.lang.IllegalArgumentException: The concrete class implementing IObjectWrapper must have exactly *one* declared private field for the wrapped object.  Preferably, this is an instance of the ObjectWrapper<T> class.
10-25 12:48:32.323 20583 20583 E AndroidRuntime: 	at com.google.tango.loader.ObjectWrapper.unwrap(ObjectWrapper.java:93)
10-25 12:48:32.323 20583 20583 E AndroidRuntime: 	at com.google.tango.jni.TangoCameraNative.initialize(TangoCameraNative.java:56)
10-25 12:48:32.323 20583 20583 E AndroidRuntime: 	at com.google.tango.loader.ITangoCameraNative$Stub.onTransact(ITangoCameraNative.java:57)
10-25 12:48:32.323 20583 20583 E AndroidRuntime: 	at android.os.Binder.transact(Binder.java:604)
10-25 12:48:32.323 20583 20583 E AndroidRuntime: 	at com.google.d.a.f.a(ITangoCameraNative.java:275)
10-25 12:48:32.323 20583 20583 E AndroidRuntime: 	at com.google.atap.tangoservice.t.a(TangoCameraNativeLoader.java:61)
10-25 12:48:32.323 20583 20583 E AndroidRuntime: 	at com.google.atap.tangoservice.Tango.<init>(Tango.java:390)

**Comment by VikAdvani** [comment]
Hi @sarathsi, did you end up solving this. I'm also seeing this issue.

**Comment by judax** [comment]
Sorry for the delay. Is this issue still happening with the latest version up in the repo?

**Comment by anutin544** [comment]
Ok

**Comment by judax** [comment]
Any update on this issue?
